
load("//:rae_rules.bzl", "rae_test")

rae_test(
    name = "call_int_return",
    src = "call_int_return.ro",
    expected = "call_int_return.out",
)

rae_test(
    name = "call_bool_return",
    src = "call_bool_return.ro",
    expected = "call_bool_return.out",
)

rae_test(
    name = "call_void_return_type",
    src = "call_void_return_type.ro",
    expected = "call_void_return_type.out",
)

rae_test(
    name = "call_pass_int",
    src = "call_pass_int.ro",
    expected = "call_pass_int.out",
)

rae_test(
    name = "call_pass_two_ints",
    src = "call_pass_two_ints.ro",
    expected = "call_pass_two_ints.out",
)

