
load("//:rae_rules.bzl", "rae_test")

rae_test(
    name = "array",
    src = "array.ro",
    expected = "array.out",
)

rae_test(
    name = "length",
    src = "length.ro",
    expected = "length.out",
)

rae_test(
    name = "set_and_access",
    src = "set_and_access.ro",
    expected = "set_and_access.out",
)